image: node:latest

stages:
    - build

build:
    stage: build
    script:
        - C:\Users\Sys.getenv('USERPROFILE')\AppData\Roaming\npm\node_modules\yarn\bin\yarn install
        - C:\Users\Sys.getenv('USERPROFILE')\AppData\Roaming\npm\node_modules\yarn\bin\yarn build
        - echo "Build successful."